export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const SET_TASKS = 'SET_TASKS'
export const DELETE_SOME_TASKS = 'DELETE_SOME_TASKS' 